version: "3.7"
services:
  database:
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgres/data
    networks:
      - default
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database 
    networks:
      - default
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  database_postgres: